# Numpy 50 Fuctions


In [2]:
#importing numy library:

import numpy as np
np.__version__

'1.18.5'

In [4]:
#function 1 creating 1D array:

a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
#2-D array:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#function 2 ndim:

a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [8]:
#function 3 itemsize:

a = np.array([(1,2,3)])
print(a.itemsize)

4


In [9]:
#function 4 dtype:

a = np.array([(1,2,3)])
print(a.dtype)

int32


In [10]:
#fuction 5 shape:

a = np.array([(1,2,3,4,5,6)])
print(a.shape)

(1, 6)


In [11]:
#function 6 reshape:

a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [12]:
#function 7 slicing:

a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [13]:
#functiion 8 linespace:

a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [14]:
#function 9 max/min:

a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [15]:
#function 10 squrae root:

a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [16]:
#function 11 addition:

x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [18]:
#function 12 subtraction:

x= np.array([(4,7,8),(6,7,9)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)


[[3 5 5]
 [3 3 4]]


In [19]:
#function 13 multiplication:

x= np.array([(4,7,8),(6,7,9)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)


[[ 4 14 24]
 [18 28 45]]


In [20]:
#function 14 devision:

x= np.array([(4,7,8),(6,7,9)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)


[[4.         3.5        2.66666667]
 [2.         1.75       1.8       ]]


In [21]:
#fuction 15 vstack:

x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [22]:
#fuction 16 hstack:

x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [23]:
#fuction 17 ravel:

x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [24]:
#function 18 arange:

b = np.arange(1,20,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
#function 19 zeroes:

c = np.zeros((5))
c

array([0., 0., 0., 0., 0.])

In [28]:
#function 20 ones:

c = np.ones((3))
c

array([1., 1., 1.])

In [29]:
#function 21 floating values arrays:

c = np.random.rand(5,4)*50
c

array([[43.88979986, 12.75540641, 31.50206742, 19.43354623],
       [33.08622081, 26.917775  ,  7.74487424, 16.74186917],
       [44.36355892, 24.08984481, 45.51651207, 47.1161934 ],
       [35.0304146 , 18.005578  , 19.00655572, 35.91730384],
       [45.99268018, 25.51586584, 45.91943156, 32.78690755]])

In [30]:
#function 22 int values arrays:

c = np.random.randint(20,size=(4,4))
c

array([[ 4, 13,  0,  6],
       [ 0, 16, 18,  4],
       [17,  8, 15, 10],
       [16,  9, 19, 19]])

In [31]:
#function 22 diagonal arrays:

array = np.eye(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
#function 23 converting data type of array:

arr = np.array([1,2,3,4,5])
arr = arr.astype(float)
arr

array([1., 2., 3., 4., 5.])

In [38]:
#function 24 taking transpose:

arr = np.array([1,2,3,4,5,6])
arr = arr.reshape((3,2))
arr = arr.T
arr

array([[1, 3, 5],
       [2, 4, 6]])

In [40]:
#function 25 resizing an array:

arr = np.array([1,2,3,4,5,6,7,8])
arr = np.resize(arr,(3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [41]:
#function 26 2d array into 1:
arr = np.array([(2,4,6),(7,5,3)])
arr = arr.flatten()
arr

array([2, 4, 6, 7, 5, 3])

In [42]:
#function 27 converting array to a list:

arr = np.array([(2,4,6),(7,5,3)])
arr = arr.tolist()
arr


[[2, 4, 6], [7, 5, 3]]

In [47]:
#function 28 sorting:

arr = np.array((6,3,9,8))
arr = np.sort(arr)
arr

array([3, 6, 8, 9])

In [50]:
#function 29 adding elements:

arr = np.array(["Asif","iqbal","Nisar"])
arr = np.append(arr,"Ali")
arr

array(['Asif', 'iqbal', 'Nisar', 'Ali'], dtype='<U5')

In [53]:
#function 30 inserting elements:

arr = np.array(["Asif","iqbal","Nisar"])
arr = np.insert(arr,1,"Ali")
arr

array(['Asif', 'Ali', 'iqbal', 'Nisar'], dtype='<U5')

In [54]:
#function 31 deleting elements:

arr = np.array(["Asif","iqbal","Nisar"])
arr = np.delete(arr,1,axis=0)
arr

array(['Asif', 'Nisar'], dtype='<U5')

In [55]:
#function 32 concatenate array:

arr1 = np.array([(4,7,9),(0,4,1)])
arr2 = np.array([(6,2,5),(6,8,3)])
arr = np.concatenate((arr1,arr2),axis=1)
arr

array([[4, 7, 9, 6, 2, 5],
       [0, 4, 1, 6, 8, 3]])

In [56]:
#function 33 spliting array:

arr1 = np.array([(4,7,9),(0,4,1)])
arr = np.array_split(arr1,3)
arr

[array([[4, 7, 9]]), array([[0, 4, 1]]), array([], shape=(0, 3), dtype=int32)]

In [57]:
#function 34 selecting element:

arr = np.array([1,2,3,4,5])
arr = arr[3]
arr

4

In [58]:
#function 35 power:

arr1 = np.array([(4,7,9),(0,4,1)])
arr2 = np.array([(6,2,5),(6,8,3)])
arr = np.power(arr1,arr2)
arr

array([[ 4096,    49, 59049],
       [    0, 65536,     1]], dtype=int32)

In [59]:
#function 36 equivalence:

arr1 = np.array([(4,7,9),(0,4,1)])
arr2 = np.array([(6,2,5),(6,8,3)])
arr = np.array_equal(arr1,arr2)
arr

False

In [60]:
#function 37 exponent:

arr = np.array([4,7,8,9])
arr = np.exp(arr)
arr

array([  54.59815003, 1096.63315843, 2980.95798704, 8103.08392758])

In [62]:
#function 38 sine:

arr = np.array([30,60,90])
arr = np.sin(arr)
arr

array([-0.98803162, -0.30481062,  0.89399666])

In [63]:
#function 39 cosine:

arr = np.array([30,60,90])
arr = np.cos(arr)
arr

array([ 0.15425145, -0.95241298, -0.44807362])

In [64]:
#function 40 tane:

arr = np.array([30,60,90])
arr = np.tan(arr)
arr

array([-6.4053312 ,  0.32004039, -1.99520041])

In [65]:
#function 41 log:

arr = np.array([30,60,90])
arr = np.log(arr)
arr

array([3.40119738, 4.09434456, 4.49980967])

In [69]:
#function 42 absolute values:

arr = np.array([1,2.6,3.5])
arr = np.abs(arr)
arr

array([1. , 2.6, 3.5])

In [70]:
#function 43 round:

arr = np.array([1,2.6,3.5,7])
arr = np.round(arr)
arr

array([1., 3., 4., 7.])

In [71]:
#function 44 round down:

arr = np.array([1,2.6,3.5,7])
arr = np.floor(arr)
arr

array([1., 2., 3., 7.])

In [74]:
#function 45 mean:

arr = np.array([[5,6,2],[6,1,4]])
arr = np.mean(arr,axis=0)
arr

array([5.5, 3.5, 3. ])

In [75]:
#function 46 median:

arr = np.array([[5,6,2],[6,1,4]])
arr = np.median(arr,axis=1)
arr

array([5., 4.])

In [78]:
#function 47 varience:

arr = np.array([[5,6,2],[6,1,4]])
arr = np.var(arr)
arr

3.6666666666666665

In [82]:
#function 48 standard deviation:

arr = np.array([2,6,3,5,9,15])
arr = np.std(arr)
arr

4.346134936801765

In [85]:
#function 49 arcsine:

arr = np.array([30,60,90])
arr = np.arcsin(arr)
arr

<ipython-input-85-80f611aafdca>:4: RuntimeWarning: invalid value encountered in arcsin
  arr = np.arcsin(arr)


array([nan, nan, nan])

In [86]:
#function 50 arccos:

arr = np.array([30,60,90])
arr = np.arccos(arr)
arr

<ipython-input-86-c13a4972e405>:4: RuntimeWarning: invalid value encountered in arccos
  arr = np.arccos(arr)


array([nan, nan, nan])